# Generated by Django 5.1.3 on 2024-12-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryID', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('capitalID', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('capitalName', models.CharField(max_length=100)),
                ('countryID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
